name: Unity CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache Library folder (Unity acceleration)
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}
          restore-keys: |
            Library-

      - name: Install Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.0.37f1  # Pas aan naar jouw Unity-versie
          targetPlatform: StandaloneWindows64  # Of Android, iOS, WebGL etc.

      - name: Build Unity project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.0.37f1
          targetPlatform: StandaloneWindows64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/StandaloneWindows64/
